<?php
namespace mobile\controllers;

use backend\models\AdminArticle;
use backend\models\AdminBuyAgent;
use backend\models\AdminCommemts;
use backend\models\AdminCommission;
use backend\models\AdminDaiList;
use backend\models\AdminGoods;
use backend\models\AdminMember;
use backend\models\AdminSetting;
use common\controllers\PublicController;
use common\models\WeChat;
use Yii;
use yii\helpers\FileHelper;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\AdminRegions;
use backend\models\AdminCategory;
use backend\models\AdminBanner;
use backend\models\AdminHandCard;
use backend\models\AdminCardProgress;
use backend\models\AdminBankCard;
use backend\models\AdminGrade;
use backend\models\AdminPay;
use yii\helpers\Url;
use AlipayTradeService;
/**
 * Site controller
 */
class ListController extends BaseController
{
    /**
     * @inheritdoc
     */
    public $defaultAction='index';
    public $enableCsrfValidation = false ;
    public $request;
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     *
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->request = Yii::$app->request;
    }
    /**
     * 购买代理
     */
    public function actionBuyAgent()
    {
        $user_id = Yii::$app->session->get('user_id');
        $user_info = AdminMember::findOne($user_id);
        $this->getView()->title = '加入会员';
        $webTitle = PublicController::getSysInfo(25);
        $poster = PublicController::getSysInfo(31);
        if(strpos($_SERVER['HTTP_USER_AGENT'],'MicroMessenger')){
            $comments = AdminCommemts::find()->joinWith('member')
                ->where(['status'=>2,'recommend'=>2])
                ->Orderby('create_time desc')
                ->offset(0)
                ->limit(2)->all();
            // 金牌会员
            $model = AdminGoods::find()->where(['id'=>4])->asArray()->one();
            return $this->render('buy-agent',compact('model','comments','user_info','poster','webTitle'));
        }else{
            if($user_id){
                $comments = AdminCommemts::find()->joinWith('member')
                    ->where(['status'=>2,'recommend'=>2])
                    ->Orderby('create_time desc')
                    ->offset(0)
                    ->limit(2)->all();
                // 金牌会员
                $model = AdminGoods::find()->where(['id'=>4])->asArray()->one();
                return $this->render('buy-agent',compact('model','comments','user_info','poster','webTitle'));
            }else{
                $sign = Yii::$app->request->get('sign');
                $invitation = Yii::$app->request->get('invitation');
                if(!empty($sign) && $sign=202){
                    $url  = Yii::$app->urlManager->createAbsoluteUrl(['index/register','invitation'=> $invitation]);
                    return $this->redirect($url);
                }else{
                    $url = Yii::$app->urlManager->createUrl('/index/index');
                    Yii::$app->getSession()->setFlash('jump', '您还未登录,点击确定登录');
                    Yii::$app->getSession()->setFlash('url', Url::toRoute(['index/login']));
                    return $this->redirect($url);
                }
            }
        }
    }

    public function actionJoinVip(){
        $model = AdminGoods::find()->orderBy('grade_id DESC')->all();
        return $this->render('buy-agent',[
            'model'=>$model,
        ]);
    } 

    public function actionVipDetails()
    {
        $this->view->title = '会员详情';
        $id = Yii::$app->request->get('id');
        $user_info = AdminMember::findOne(Yii::$app->session->get('user_id'));
        $model = AdminGoods::find()->where(['id'=>$id])->one();
        return $this->render('vip-details',[
            'model'=>$model,
            'user_info'=>$user_info,
        ]);
    }
    /**
     * 评论
     */
    public function actionComment()
    {
        $this->getView()->title = '评论列表';
       // $id = Yii::$app->request->get('grade_id')?:1;
        $pageSize = 10;
        $model = AdminCommemts::find()->joinWith('member')
            ->andwhere(['status'=>2,'recommend'=>2])
          //  ->andwhere(['grade_id'=>$id])
            ->orderBy('create_time DESC')
            ->offset(0)
            ->limit($pageSize)
            ->all();
        return $this->render('comment',[
            'model'=>$model,
        ]);
    }

    /**
     * 发布评价
     */
    public function actionSubComment()
    {
        $this->getView()->title = '发布评价';
        $grade_id = Yii::$app->request->get('grade_id');
        if(Yii::$app->request->isPost) {
            $grade_id = Yii::$app->request->post('grade_id');
            $content = PublicController::filter(Yii::$app->request->post('content'));
            $comment = new AdminCommemts();
            $comment->user_id = Yii::$app->session->get('user_id');
            $comment->content = $content;
            $comment->create_time = time();
            $comment->recommend = 1;
            $comment->status = 1;
            $comment->grade_id = $grade_id;
            if($comment->save(false)) {
                return 100;
            }else {
                return 200;
            }
        }
        return $this->render('sub-comment',[
            'grade_id'=>$grade_id,
        ]);
    }

    /**
     * 填写资料
     */
    public function actionSubData()
    {
        $this->getView()->title = '提交支付';
        $user_id = Yii::$app->session->get('user_id');
        $user_info = AdminMember::findOne($user_id);
        if(!$user_info){
            $url = Yii::$app->urlManager->createUrl('/index/login');
            return $this->redirect($url);
        }
        $price = AdminGoods::findOne(['id'=>4])->price;
        if ($user_id == 9290) {
            $price = 0.01;
        }
        $pay_ways = AdminPay::find()->where(['is_open'=>1])->asArray()->all();
        if(Yii::$app->request->isPost) {
//            if ($user_id != 9290) {
//                return $this->json(100,'接口维护中。。。');
//            }
            $type = PublicController::filter($this->request->post('type'));
            $member = AdminMember::findOne($user_id);
            if($member->grade == 3 ){
                return $this->json(100,'您已经是金牌会员，无需重复购买');
            }
            $agent = new AdminBuyAgent();
            $commission = new AdminCommission();
            $member->update_time = time();
            $agent->user_id = $user_id;
            $agent->money = $price;
            $agent->created_time = time();
            $agent->status = 0;
            $agent->order_sn = $this->payOrdersId();
            $agent->type = $type;
            $agent->grade_id = 3;
            $commission->order_sn = $agent->order_sn;
            $commission->status = 0;
            $commission->user_id = $user_id;
            $commission->created_time = time();
            $transaction = Yii::$app->db->beginTransaction();
            if ($member->validate() && $agent->validate()) {
                try {
                    $member->save();
                    $agent->save();
                    $commission->save(false);
                    $transaction->commit();
                    setcookie("order_sn", $agent->order_sn , time()+600);
                    setcookie("money", $price, time()+600);
                    setcookie("order_id", $agent->id, time()+600);
                    Yii::$app->session->set('order_sn',$agent->order_sn);
                    Yii::$app->session->set('money',$price);
                    Yii::$app->session->set('order_id',$agent->id);
                    $url = Url::to(['list/cj', 'order_id' => $agent->order_sn]);
                    return json_encode(['status'=>200,'order_id'=>$agent->order_sn, 'url' => $url]);
                } catch (\Exception $e) {
                    //捕获错误
                    $transaction->rollback();
                    return $this->json(100,'提交失败，请稍后重试');
                }
            }else{
                return $this->json(100,'提交失败，请稍后重试');
            }
        }
        return $this->render('sub-data',compact('user_info','price','pay_ways'));
    }

    /**
     * 生成流水号
     */
    protected function payOrdersId()
    {
        return date('YmdHis') . str_pad(mt_rand(1, 99999), 5, '0', STR_PAD_LEFT);
        //return date('YmdHis').uniqid(); 
    }

    /*
        线下上传支付截图
    */
    public function actionUpimg()
    {
        $user_id = Yii::$app->session->get('user_id');
        $name = Yii::$app->session->get('name');
        $is_open = Yii::$app->session->get('is_open');
        $money = Yii::$app->session->get('money');
        $status = Yii::$app->session->get('status');
        $pay_types = Yii::$app->session->get('pay_types');
        $grade = Yii::$app->session->get('grade');
        $order_sn = $this->payOrdersId();
        $agent = AdminBuyAgent::find()->where(['type' => 3, 'user_id' => $user_id, 'grade_id' => $grade])->one();
        $member = AdminMember::findOne(Yii::$app->session->get('user_id'));
        if ($agent) {
            if (Yii::$app->request->isPost) {
                $content = $this->request->post('content');
                if (strlen($content) > 100) {
                    Yii::$app->session->setFlash('file2', '1');
                    return $this->redirect(array('upimg'));
                }
                // echo "33";exit;
                if (isset($_FILES['idcard_face']['name'])) {
                    $idcard_face = $this->uploadfile($_FILES['idcard_face']);
                } else {
                    Yii::$app->session->setFlash('file', '1');
                    return $this->redirect(array('upimg'));
                    // $idcard_face = $agent->img;
                }
                $commission = AdminCommission::find()->where(['order_sn' => $agent->order_sn])->one();
                $agent->user_id = $user_id;
                $agent->money = $money;
                $agent->created_time = time();
                $agent->status = 0;
                $agent->order_sn = $agent->order_sn;
                $agent->type = $pay_types;//支付方式
                $agent->img = $idcard_face;
                $agent->content = $content;
                $agent->status = -2; //待审核
                $agent->grade_id = $grade;
                $member->real_name = $name;
                $member->update_time = time();
                $member->is_open = $is_open;
                $commission->order_sn = $agent->order_sn;
                $commission->status = 0;
                $transaction = Yii::$app->db->beginTransaction();
                if ($member->validate() && $agent->validate()) {
                    try {
                        $member->save();
                        $agent->save();
                        $commission->save(false);
                        $transaction->commit();
                        echo "<script>alert('申请中，请等待审核');window.location.href='/index.php?r=member/index'</script>";
                    } catch (Exception $e) {
                        //捕获错误
                        $transaction->rollback();
                        echo "<script>alert('系统错误');window.location.href='/index.php?r=list/upimg'</script>";
                    }
                } else {
                    return 3000;
                }
            }
        } else {
            $agent2 = new AdminBuyAgent();
            $commission2 = new AdminCommission();
            if (Yii::$app->request->isPost) {
                $content = $this->request->post('content');
                if (strlen($content) > 100) {
                    Yii::$app->session->setFlash('file2', '1');
                    return $this->redirect(array('upimg'));
                }
                if ($_FILES['idcard_face']['name']) {
                    $idcard_face = $this->uploadfile($_FILES['idcard_face']);
                } else {
                    Yii::$app->session->setFlash('file', '1');
                    return $this->redirect(array('upimg'));
                    $idcard_face = $agent->img;
                }
                $agent2->user_id = $user_id;
                $agent2->money = '';
                $agent2->created_time = time();
                $agent2->status = 0;
                $agent2->order_sn = $order_sn;
                $agent2->type = $pay_types;//支付方式
                $agent2->img = $idcard_face;
                $agent2->content = $content;
                $agent2->status = -2; //待审核
                $agent2->grade_id = $grade;
                $member->real_name = $name;
                $member->update_time = time();
                $member->is_open = $is_open;
                $commission2->order_sn = $order_sn;
                $commission2->status = 0;
                $transaction = Yii::$app->db->beginTransaction();
                if ($member->validate() && $agent2->validate()) {
                    try {
                        $member->save();
                        $agent2->save();
                        $commission2->save(false);
                        $transaction->commit();
                        echo "<script>alert('申请中，请等待审核');window.location.href='/index.php?r=member/index'</script>";
                    } catch (Exception $e) {
                        //捕获错误
                        $transaction->rollback();
                        echo "<script>alert('系统错误');window.location.href='/index.php?r=list/upimg'</script>";
                    }
                } else {
                    return 3000;
                }
            }
        }
        if ($agent) {
            switch ($agent->status) {
                case -2;
                    $msg = '待审核';
                    break;
                case 1;
                    $msg = '审核通过,请勿再次提交！';
                    break;
                case -1;
                    $msg = '审核拒绝';
                    break;
            }
            $order = $agent->order_sn;
        } else {
            $msg = '待申请';
            $order = '';
        }
        return $this->render('upimg', [
            'agent' => $agent,
            'msg' => $msg,
            'order' => $order,
        ]);

    }

      // 上传图片
    public function uploadfile($file='')
    {
        $timefile=date("Y-m-d");
        $uploaddir = 'uploads/img/'.$timefile."/";
//         if(!is_readable($uploaddir))
//           {
//
//             is_file($uploaddir) or mkdir($uploaddir,0777);
//           }
        if(!file_exists($uploaddir)){
            if(!FileHelper::createDirectory($uploaddir)){
                return false;
            }
        }
        $info=pathinfo($file['name'],PATHINFO_EXTENSION);
        $dir=$uploaddir .date('Ymd').rand(10000,99999).'.'.$info;
        if (move_uploaded_file($file['tmp_name'],$dir)) {
            $re['dir']='/'.$dir;
            $re['msg']="上传成功";
            $re['status']=200;
            return $re['dir'];
        } else {
            $re['msg']="上传失败";
            echo $re['msg'];exit;
        }
    }

    /**
     * 办卡进度
     */
    public function actionCardRate()
    {
        $this->getView()->title = '办卡进度';
        if(strpos($_SERVER['HTTP_USER_AGENT'],'MicroMessenger')){
            $process1=AdminCardProgress::find()->where(['type'=>1])->all();
            $process2=AdminCardProgress::find()->where(['type'=>2])->all();
            return $this->render('card-rate',[
                'process1'=>$process1,
                'process2'=>$process2,
            ]);
        }else
        {
            $user_id = Yii::$app->session->get('user_id');
            if($user_id){
                $process1=AdminCardProgress::find()->where(['type'=>1])->all();
                $process2=AdminCardProgress::find()->where(['type'=>2])->all();
                $user_info = AdminMember::findOne($user_id);
                return $this->render('card-rate',[
                    'process1'=>$process1,
                    'process2'=>$process2,
                    'user_info'=>$user_info,
                ]);
            }else{
                $url = Yii::$app->urlManager->createUrl('/index/index');
                Yii::$app->getSession()->setFlash('jump', '您还未登录,点击确定登录');
                Yii::$app->getSession()->setFlash('url', Url::toRoute(['index/login']));
                $this->redirect($url);Yii::$app->end();
            }
        }
    }

    /**
     * 提额技巧
     */
    public function actionNews( $cat_id='4' )
    {
        $user_id = Yii::$app->session->get('user_id');
         if(strpos($_SERVER['HTTP_USER_AGENT'],'MicroMessenger')){
            $user_info = AdminMember::findOne($user_id);
           if(!($user_info->tel)){
                $urls= Yii::$app->urlManager->createAbsoluteUrl(['list/buy-agent']);
                $this->redirect($urls);
                Yii::$app->end();
           }
         }
        $this->getView()->title = AdminCategory::findOne($cat_id)->name;
        //获取分类
        $array=['0'=>4,'1'=>5,'2'=>6,'3'=>7];
        $cat_list = AdminCategory::find()->where(['in','id',$array])->all();
        //对应分类下面的文章
        $new  = AdminArticle::find()->andwhere('cat_id='.$cat_id)->Orderby('create_time desc')->offset(0)->limit(8)->all();
        //顶部轮播推荐文章
        $top_news =AdminArticle::find()->where(['is_recom'=>2])->all();
        return $this->render('news',[
            'cat_list'=>$cat_list,
            'new' =>$new,
            'top_news'=>$top_news,
        ]);
    }

    /**
     * @return string
     * 搜索
     */
     public function actionKeywords(){
         $keywords = Yii::$app->request->get('keywords');
         $this->getView()->title = $keywords;
         $cat_id  =Yii::$app->request->get('cat_id');
         //获取分类
         $cat_list = AdminCategory::find()->where(['in','id',[4,5,6,7]])->all();
         //对应搜索条件下面的文章
         $new  = AdminArticle::find()->andwhere('cat_id='.$cat_id)->andwhere(['like','title',$keywords])->Orderby('create_time desc')->offset(0)->limit(8)->all();
         //顶部轮播推荐文章
         $top_news =AdminArticle::find()->where(['is_recom'=>2])->all();
         return $this->render('news',[
             'cat_list'=>$cat_list,
             'new'     =>$new,
             'top_news'=>$top_news,
             'keywords'=>$keywords,
         ]);
     }


    /**
     * 详情
     */
    public function actionDetail($id)
    {
        $this->view->title = '文章详情';
        $model=AdminArticle::findOne($id);
         return $this->render('detail',[
            'model'=>$model,
         ]);
    }

    /**
     * @return int
     * 权限判断
     */
    public function actionPermission(){

        $user_id = Yii::$app->session['user_id'];
        $id =Yii::$app->request->get('id');
        $status=Yii::$app->request->get('status');
        if($user_id){
            $member=AdminMember::findOne($user_id);
            if($member->agent==0){
                return 100; //是代理商
            }else{
                if($status==1){
                    $permiss=AdminArticle::findOne($id);
                }else if($status==2){
                    $permiss=AdminHandCard::findOne($id);
                }else if($status==3){
                    $permiss=AdminCardProgress::findOne($id);
                }
                if ($permiss->permission==0) {
                      return 300;
                }else{
                     return 400;
                }
            }
        }else{
            return 200;
        }
    }

    /**
     * 银行快贷
     * 权限判断
     * 
     */
    public function actionLoadPermission(){
        $user_id=Yii::$app->session['user_id'];
        $id = Yii::$app->request->get('id');
        if($user_id){
            $member=AdminMember::findOne($user_id);
            if($member->agent==1){
                return 100;
            }else{
                $loan=AdminBanKCard::findOne($id);
                if($loan->permission==0){
                    return 300;
                }else{
                    return 400;
                }
            }
        }
    }

    /**
     * 银行快贷
     * $type 3，信用卡贷，2，银行快贷
     * $type 1，热门推荐
     */
    public function actionBankLoan($type=1)
    {
        $user_id = Yii::$app->session->get('user_id');
         if(strpos($_SERVER['HTTP_USER_AGENT'],'MicroMessenger')){
            $user_info = AdminMember::findOne($user_id);

         }
        $type_info = ['1'=>'热门推荐','2'=>'银行快贷','3'=>'信用卡贷'];
        $this->getView()->title = $type_info[$type];
        if($type==1||$type==2){
            $creditcard = AdminBanKCard::find()->andwhere(['type'=>$type])
            //->andwhere(['recommend'=>0])
            ->Orderby('create_time desc')
            ->offset(0)->limit(8)
            ->all();
        }else{
            $creditcard =   AdminBanKCard::find()->where(['recommend'=>1])->Orderby('create_time desc')->offset(0)->limit(8)->all();
        }
        $dai_list = AdminDaiList::find()->all();
        return $this->render('bank-loan',[
            'creditcard'=>$creditcard,
            'dai_list'=>$dai_list,
        ]);
    }

    /**
     * 单页
     */
    public function actionPage( $id=1 )
    {
        $model = AdminArticle::find()->where(['art_id'=>$id])->one();
        $this->getView()->title = $model->title;
        return $this->render('page',[
            'model'=>$model,
        ]);
    }

    // app下载
    public function actionAppDownload()
    {
        $url = PublicController::getSysInfo(33);
        return $this->redirect($url);
    }

    public function actionContactus(){
        $this->getView()->title = '客服';
        $kefu = PublicController::getSysInfo(15);
        $kefu2 =explode(',', $kefu);
        return $this->render('contactus',[
            'kefu2'=>$kefu2,
        ]);

    }
    public function actionWx(){
        $this->getView()->title = '微信客服';
        return $this->render('wx',[

        ]);
    }
    // 提额技巧加载更多
    public function actionNewsMore($cat_id=4){
        $page = Yii::$app->request->get('page');
        $page_size = 8;
        $li='';
        $new  = AdminArticle::find()->andwhere('cat_id='.$cat_id)
                ->Orderby('create_time desc')
                ->offset(($page)*$page_size)
                ->limit($page_size)
                ->asArray()
                ->all();
        foreach ($new as $value) {
                $li .= '<li><a onclick="find_new('.$value['art_id'].')">';
                $li .= '<img src="'.$value['img'].'" class="fl"/>';
                $li .= '<p>'.PublicController::substr($value['title'], 20).'</p>';
                $li .= '<span>'.date('Y-m-d',$value['create_time']).'</span><div class="clear"></div></a></li>';
        }
        return $li;
    }

    //银行快贷加载更多 
    public function actionBankMore($type=1){

        $page = Yii::$app->request->get('page');
        $page_size = 8;
        $li='';
        if($type==1||$type==2){
            $creditcard = AdminBanKCard::find()->andwhere(['type'=>$type])
            ->andwhere(['recommend'=>0])
            ->orderBy('create_time desc')
            ->offset($page*$page_size)
            ->limit($page_size)
            ->asArray()
            ->all();
        }else{
            $creditcard = AdminBanKCard::find()->where(['recommend'=>1])
            ->Orderby('create_time desc')
            ->offset(($page)*$page_size)
            ->limit($page_size)
            ->asArray()
            ->all();
  
        }
        foreach ($creditcard as  $value) {
               $li .=' <li><img src="'.$value['logo'].'" class="fl"/>';
               $li .=' <p class="imcl1"><span>'.PublicController::substr($value['title'], 8).'</span><strong class="fr">'.$value['price'].'万元</strong></p>';
               $li .=' <h2 class="imcl2"><em>凭身份证可达3万 已申请人数：3195</em><em class="fr">通过率：<i>'.$value['rate'].'%</i></em></h2>';
               $li .=' <div class="clear"></div></li>';
        }
        return $li;

    }
    /**
     * 加载更多
     */
    public function actionLoadMore($type=1)
    {   $id =  Yii::$app->request->get('grade_id');
        $page = Yii::$app->request->get('page');
        $page_size = 1;
        $li = '';
        $model = AdminCommemts::find()->joinWith('member')
            ->andwhere(['status'=>2,'recommend'=>2])
            ->andwhere(['grade_id'=>$id])
            ->orderBy('create_time DESC')
            ->offset(($page-1)*$page_size)
            ->limit($page_size)
            ->all();
        foreach ($model as $list) {
            $li .= '<li><div class="bmpl_left fl"><img src="'.$list->member['pic'].'"></div><div class="bmpl_right fl">';
            $li .= '<h1><span>'.$list->member['nickname'].'</span>';
            $li .= '<i class="fr">'.date('Y-m-d',$list->create_time).'</i></h1>';
            $li .= '<p>'.$list->content.'</p></div><div class="clear"></div></li>';
        }
        return $li;
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $user_id = Yii::$app->session->get('user_id');
        $user_info = AdminMember::findOne($user_id);
        $weChat = new WeChat();
        return $this->render('index');
    }

    /**
     * 验证手机号码和验证码
     * @return integer
     */
    protected function validateCode( $tel='', $code='' )
    {
        $code_tel = Yii::$app->session->get('send_tel');
        $code_num = Yii::$app->session->get('send_code');
        if($tel != $code_tel) {
            return 200;     //不是当前手机号
        }else if(!$code_num) {
            return 300;     //验证码不正确
        }else if($code != $code_num) {
            return 300;
        }else{
            return 100;
        }
    }

        /**
     * 发送短信配置信息
     */
    public function actionSms($tel, $temp='SMS_114140002')
    {
        $code = rand(100000, 999999);
       
        //$param['SMS_7785270'] = json_encode(['code'=>$code,'product'=>'卡农社区']);
        $param = json_encode(['code'=>"$code"]);
        Yii::$app->session->set('send_code',$code);
        Yii::$app->session->set('send_tel',$tel);
        return PublicController::sendSms($tel,$param,$temp);
    }


    /**
     * 判断是否支付
     */
    public function actionIsPay()
    {   
        // file_put_contents('ceshi2.txt',33333);
        //$order_sn = Yii::$app->request->post('order_sn');
        $order_sn = Yii::$app->session->get('order_sn');
        $model = AdminBuyAgent::find()->where(['order_sn'=>$order_sn])->one();
        if($model->status==1) {
            $arr['state'] = 100;
            $arr['order_id'] = $model->order_sn;
        }else{
            $arr['state'] = 200;
            $arr['order_id'] = $model->order_sn;
        }
        return json_encode($arr);
    }

    /**
     * 异步处理购买后的数据 
     */
    public function actionDell()
    {
        header("Content-type:text/html;charset=utf-8");
        $order_sn = Yii::$app->request->get('order_id');
        $model = AdminBuyAgent::find()->where(['order_sn' => $order_sn,'status' => 1])->one();
        $member = AdminMember::find()->where(['id' => $model->user_id])->one();
        $grade_id = $model->grade_id;
        if ($grade_id == 1) {
            $msg = '铜牌会员';
        } elseif ($grade_id == 2) {
            $msg = '银牌会员';
        } elseif ($grade_id == 3) {
            $msg = '金牌会员';
        }
        /**********支付成功通知end**********/
        if ($member->grade != $grade_id) {
            $member->grade = $grade_id;
            // $member->agent = 1;
            $member->save(false);
            if ($member->is_open == 1) {
                $title = '购买成功';
                $content = "您已经成功加入会员，赶快行动吧！";
                BaseController::writeNotice($member->id,$title,$content);

                $url = Yii::$app->request->hostInfo."/index.php?r=index%2Findex&type=1";
                $temp = Yii::$app->params['wx']['sms']['buy_success'];
                $data['first'] = ['value' => '您好,您已成功成为' . $msg, 'color' => '#173177'];
                $data['keyword1'] = ['value' => '***会员卡', 'color' => '#173177'];
                $data['keyword2'] = ['value' => date('Y-m-d H:i', $model->created_time), 'color' => '#173177'];
                $data['keyword3'] = ['value' => '购买成功', 'color' => '#173177'];
                $data['keyword4'] = ['value' => $model->money, 'color' => '#173177'];
                $data['remark'] = ['value' => '您已经成功加入' . $msg . ',赶快行动吧!', 'color' => '#173177'];
                PublicController::sendTempMsg($temp, $member->openid, $data, $url);
            }
        }
        //查找上级
        $pre_member = AdminMember::find()->where(['invitation' => $member->bei_invitation])->one(); //1级
        $pre_member2 = AdminMember::find()->where(['invitation' => $pre_member->bei_invitation])->one();//2级
        $pre_member3 = AdminMember::find()->where(['invitation' => $pre_member2->bei_invitation])->one();//3级
        $pre_commission=PublicController::commission($model->money,$pre_member->grade,1);
        $pre_commission2=PublicController::commission($model->money,$pre_member->grade,2);
        $pre_commission3=PublicController::commission($model->money,$pre_member->grade,3);
        if ($pre_member) {
            //获取返佣比例
            $commission = AdminCommission::find()->where(['order_sn' => $order_sn])->one();
            if ($commission->status == 0) {
                $pre_member->promotion_commission += $pre_commission;
                $pre_member->available_money += $pre_commission;
                //生成返佣明细
                $commission->user_id = $pre_member->id;//用户id
                $commission->jy_user_id = $model->user_id;//交易人
                $commission->type = 1;
                $commission->status = 1;
                $commission->money = $model->money;
                $commission->commission_money = $pre_commission;
                $commission->created_time = time();
                $commission->openid = $pre_member->openid;
                $commission->jy_openid = $member->openid;
                $commission->save(false);
                $pre_member->save(false);
                if ($pre_member2 && $pre_commission2 != 0) { //2级
                    $commission = new AdminCommission();
                    $pre_member2->promotion_commission += $pre_commission2;
                    $pre_member2->available_money += $pre_commission2;
                    $commission->user_id = $pre_member2->id;
                    $commission->jy_user_id = $model->user_id;
                    $commission->type = 1;
                    $commission->status = 1;
                    $commission->money = $model->money;
                    $commission->commission_money = $pre_commission2;
                    $commission->created_time = time();
                    $commission->openid = $pre_member2->openid;
                    $commission->jy_openid = $member->openid;
                    $commission->save(false);
                    $pre_member2->save(false);
                }
                if ($pre_member3 && $pre_commission3 != 0) {  //3级\
                    $commission = new AdminCommission();
                    $pre_member3->promotion_commission += $pre_commission3;
                    $pre_member3->available_money += $pre_commission3;
                    $commission->user_id = $pre_member3->id;
                    $commission->jy_user_id = $model->user_id;
                    $commission->type = 1;
                    $commission->status = 1;
                    $commission->money = $model->money;
                    $commission->commission_money = $pre_commission3;
                    $commission->created_time = time();
                    $commission->openid = $pre_member3->openid;
                    $commission->jy_openid = $member->openid;
                    $commission->save(false);
                    $pre_member3->save(false);
                }
                /**********上级推送**********/
                //判断上级是否开启推送
                $temp = Yii::$app->params['wx']['sms']['income_receive'];
                if ($pre_member->is_open == 1) {
                    $title = "佣金到账提醒";
                    $content = "{$member->nickname}成功购买，已到您账户。收益金额：{$pre_commission}元；到账时间：".date('Y-m-d H:i', $model->created_time);
                    BaseController::writeNotice($pre_member->id,$title,$content);

                    $url = Yii::$app->request->getHostInfo() . '/index.php?r=member%2Faccount';
                    $data['first'] = ['value' => '佣金到账提醒', 'color' => '#173177'];
                    $data['income_amount'] = ['value' => $pre_commission . '/元', 'color' => '#173177'];
                    $data['income_time'] = ['value' => date('Y-m-d H:i', $model->created_time), 'color' => '#173177'];
                    $data['remark'] = ['value' => $member->nickname . "成功购买，已到您账户", 'color' => '#173177'];
                    PublicController::sendTempMsg($temp, $pre_member->openid, $data, $url);
                }
                if ($pre_member2->is_open == 1 && $pre_commission2 != 0) {
                    $title = "佣金到账提醒";
                    $content = "{$member->nickname}成功购买，已到您账户。收益金额：{$pre_commission}元；到账时间：".date('Y-m-d H:i', $model->created_time);
                    BaseController::writeNotice($pre_member->id,$title,$content);

                    $url = Yii::$app->request->getHostInfo() . '/index.php?r=member%2Faccount';
                    $data['first'] = ['value' => '佣金到账提醒', 'color' => '#173177'];
                    $data['income_amount'] = ['value' => $pre_commission2 . '/元', 'color' => '#173177'];
                    $data['income_time'] = ['value' => date('Y-m-d H:i', $model->created_time), 'color' => '#173177'];
                    $data['remark'] = ['value' => $member->nickname . "成功购买，已到您账户", 'color' => '#173177'];
                    PublicController::sendTempMsg($temp, $pre_member2->openid, $data, $url);
                }
                if ($pre_member3->is_open == 1 && $pre_commission3 != 0) {
                    $title = "佣金到账提醒";
                    $content = "{$member->nickname}成功购买，已到您账户。收益金额：{$pre_commission}元；到账时间：".date('Y-m-d H:i', $model->created_time);
                    BaseController::writeNotice($pre_member->id,$title,$content);

                    $url = Yii::$app->request->getHostInfo() . '/index.php?r=member%2Faccount';
                    $data['first'] = ['value' => '佣金到账提醒', 'color' => '#173177'];
                    $data['income_amount'] = ['value' => $pre_commission3 . '/元', '                        color' => '#173177'];
                    $data['income_time'] = ['value' => date('Y-m-d H:i', $model->created_time), 'color' => '#173177'];
                    $data['remark'] = ['value' => $member->nickname . "成功购买，已到您账户", 'color' => '#173177'];
                    PublicController::sendTempMsg($temp, $pre_member3->openid, $data, $url);
                }
            }
            return true;
            Yii::$app->end();
            /***********上级推送end*********/
        } else {
            return true;
            Yii::$app->end();
        }
    }
    /**
     * 常见问题
     * @param int $cat_id
     * @return string
     */
    public function actionQuestions($cat_id=10){
        $user_id = Yii::$app->session->get('user_id');
         if(strpos($_SERVER['HTTP_USER_AGENT'],'MicroMessenger')){
            $user_info = AdminMember::findOne($user_id);
           if(!($user_info->tel)){
                $urls= Yii::$app->urlManager->createAbsoluteUrl(['list/buy-agent']);
                $this->redirect($urls);
                Yii::$app->end();
           }
         }
        $model = AdminArticle::find()->where(['cat_id'=>$cat_id])->Orderby('create_time desc')->offset(0)->limit(10)->all();
        $this->getView()->title = '常见问题';
        return $this->render('questions',[
            'model'=>$model,
        ]);
    }


    /**
     * 常见问题加载更多
     */
    public function actionQuestionsMore($cat_id=10)
    {
        $page = Yii::$app->request->get('page');
        $page_size = 10;
        $li='';
        $model  = AdminArticle::find()->andwhere('cat_id='.$cat_id)
                ->Orderby('create_time desc')
                ->offset(($page)*$page_size)
                ->limit($page_size)
                ->asArray()
                ->all();
        foreach ($model as $value) {

                $li .='<li><a href="index.php?r=list/detail&id='.$value['art_id'].'"><p>'.PublicController::substr($value['title'], 20).'</p>';
                $li .='<span>'.date('Y-m-d',$value['create_time']).''; 
                $li .='</span><div class="clear"></div></a></li>';
        }

        return $li;
    }


    public function actionOrderpay()
    {
        $order_id = Yii::$app->request->get('id');
        $model = AdminBuyAgent::findOne($order_id);
        $order_sn = Yii::$app->session->get('order_sn');
        $money = Yii::$app->session->get('money');
        $model->save(false);
        if($model && $model->status === 0) {
            $data['out_trade_no'] = $order_sn;
            $data['subject'] = '支付';
            $data['total_amount'] = $money;
            $data['body'] = 'test';
            $url = Yii::$app->request->hostInfo."/mobilealipay/alipay/wappay/pay.php";
            PublicController::build_form($url, $data);
        }else {
            exit('系统出错');
        }
    }


    /**
     * 同步回调
     */
    public function actionReturn()
    {
        $root = Yii::getAlias('@root');
        require_once $root.'/mobilealipay/alipay/config.php';
        require_once $root.'/mobilealipay/alipay/wappay/service/AlipayTradeService.php';
        $alipaySevice = new AlipayTradeService($config);
        $arr=$_GET;
        unset($arr['r']);
        // file_put_contents('258.txt',json_encode($_GET));
        $result = $alipaySevice->check($arr);
        if($result) { //验证成功
            $str = $arr['out_trade_no'];
            //支付宝交易号
            // $trade_no = htmlspecialchars($arr['trade_no']);

             return $this->redirect(['index/index']);

        }else{
            //验证失败
            echo "验证失败";
        }
    }


    /**
     * 异步回调
     */
    public function actionNotify()
    {   
        // file_put_contents('6666666.txt',222);
        $root = Yii::getAlias('@root');
        require_once $root.'/mobilealipay/alipay/config.php';
        require_once $root.'/mobilealipay/alipay/wappay/service/AlipayTradeService.php';
        $arr = $_POST;
        // file_put_contents('22222222.txt',json_encode($arr));
        $alipaySevice = new AlipayTradeService($config);
        $alipaySevice->writeLog(var_export($_POST,true));
        $result = $alipaySevice->check($arr);
        if($result) {//验证成功
            // file_put_contents('zf1.txt',$arr);
            //$out_trade_no = json_decode(Yii::$app->request->post('out_trade_no'),true);
            $str = Yii::$app->request->post('out_trade_no');
            //支付宝交易号
            $trade_no = Yii::$app->request->post('trade_no');
            //支付金额
            $money = Yii::$app->request->post('total_amount');
            //交易状态
            // file_put_contents('1.txt',$str);
            $trade_status = Yii::$app->request->post('trade_status');

            if($_POST['trade_status'] == 'TRADE_FINISHED') {
                //退款日期超过可退款期限后（如三个月可退款），支付宝系统发送该交易状态通知
            }
        else if ($_POST['trade_status'] == 'TRADE_SUCCESS') {

             $model = AdminBuyAgent::find()->where(['order_sn'=>$str])->one();    
             $member = AdminMember::findOne($model->user_id);
             $member->agent = 1;
             $member->save(false);
             $pre_member = AdminMember::find()->where(['invitation'=>$member->bei_invitation])->one();
        if($pre_member) {
            //获取返佣比例
            $rate = intval(PublicController::getSysInfo(7));
            $pre_member->promotion_commission += number_format($model->money*$rate/100,2);
            $pre_member->available_money += number_format($model->money*$rate/100,2);
            //生成返佣明细
            $commission = new AdminCommission();
            $commission->user_id = $pre_member->id;
            $commission->jy_user_id = $model->user_id;
            $commission->type = 1;
            $commission->money = $model->money;
            $commission->commission_money = number_format($model->money*$rate/100,2);;
            $commission->created_time = time();
            $commission->openid = $pre_member->openid;
            $commission->jy_openid = $member->openid;
            $commission->save(false);
            $pre_member->save(false);
            /**********上级推送**********/
            //判断上级是否开启推送
            /***********上级推送end*********/
        }
            //付款完成后，支付宝系统发送该交易状态通知
        }
            echo "success"; //请不要修改或删除
        }else {
            echo "fail";
        }
    }
    /**
     * 支付宝支付
     */
    public function actionCj()
    {
        $orderId = $this->request->get('order_id');
        $order = AdminBuyAgent::findOne(['order_sn'=>$orderId]);
        if($order->status!=0){
            yii::$app->getSession()->setFlash('error','系统错误');
            echo "<script>window.history.go(-1)</script>";
            exit();
        }else{
            if (strpos($_SERVER['HTTP_USER_AGENT'], 'MicroMessenger')){
                echo '<img src="/mobile/web/images/llq_zf.png" style="width: 100%">';exit;
            }else{
                $model = array(
                    'order_sn'=>$order->order_sn,
                    'money'=>$order->money,
                );
//                $url = Yii::$app->request->getHostInfo().'/mobilealipay/alipay/wappay/pay.php';
                $url = Url::to(['list/alipay']);
                PublicController::build_form($url,$model);
            }
        }
    }

    public function actionAlipay()
    {
        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            return $this->render('alipay', compact('post'));
        }
    }



}
