<?php
namespace mobile\controllers;

use backend\models\AdminAgentMessage;
use backend\models\AdminDaiProduct;
use backend\models\AdminDaiRecord;
use backend\models\AdminMember;
use common\controllers\PublicController;
use common\utils\CommonFun;
use Yii;
use yii\web\Controller;

/**
 * Site controller
 */
class OtherController extends controller
{

    public $enableCsrfValidation = false ;
    public $request;
    public $session;
    public $user_id;

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->request = Yii::$app->request;
        $this->session = Yii::$app->session;
        $this->user_id = $this->session->get('user_id');
    }

    /**
     * 客户申请页面
     */
    public function actionSubProduct()
    {
        $this->getView()->title = '提交信息';
        if($this->request->isPost) {
            $name = Yii::$app->request->post('name');
            $tel = Yii::$app->request->post('tel');
            $idCard = Yii::$app->request->post('id_card');
            $uid = Yii::$app->request->post('uid');
            $pid = Yii::$app->request->post('pid');
            $sign = Yii::$app->request->post('sign');// 新增sign 判断融资客
            $dai_record = new AdminDaiRecord();
            $dai_record->user_id = $this->user_id;
            $dai_record->name = $name;
            $dai_record->tel = $tel;
            $dai_record->ip = CommonFun::getClientIp();
            $dai_record->phone_system = PublicController::getSystem();
            $dai_record->created_time = time();
            $dai_record->match_time = time();
            $dai_record->tid = $uid;
            $dai_record->pid = $pid;
            if ($idCard) { // 存在说明用户勾选了保险接口协议
                $dai_record->id_card = $idCard;
                if (!PublicController::isIdCard($idCard)) {
                    Yii::$app->getSession()->setFlash('error', '身份证号码不正确');
                    echo "<script>window.history.go(-1)</script>";return;
                }
                // 保险接口发送数据
                $res = PublicController::yyangApi($name, $tel, $idCard);
                $apiData = json_encode($res, JSON_UNESCAPED_UNICODE);
                $dai_record->api_data = $apiData;
            }
            // 去除空白数据
            if(!$name || !$tel){
                return '必填项不能为空';
            }
            $hasExist = AdminDaiRecord::findOne(['tel' => $tel, 'pid' => $pid]);
            if($sign==101){
                $modelsign = AdminDaiProduct::findOne($pid);
                $dai_record->sign = $sign;
                if($hasExist || $dai_record->save()){
                    if($modelsign->links){
                        return $this->redirect($modelsign->links);
                    }else{
                        $url = Yii::$app->urlManager->createAbsoluteUrl(['index/wantloan']);
                        return $this->redirect($url);
                    }
                }else{
                    Yii::$app->getSession()->setFlash('error', '提交失败，请重新提交！');
                    echo "<script>window.history.go(-1)</script>";return;
                }
            }
            if($hasExist || $dai_record->save(false)) {   // ||:前面为true，后面的不会执行
                $model = AdminDaiProduct::find()->where(['id'=>$pid])->one();
                //查找上级
                $pre_member = AdminMember::findOne($dai_record->tid);
                if($pre_member && $pre_member->is_open) {
                    $title = "您的好友在您的推荐下申请了{$model->title}";
                    $content = "申请人：".$dai_record->name."；申请时间：".date('Y-m-d H:i',$dai_record->created_time)."；手机号码：".substr_replace($dai_record->tel,'****',3,4);
                    BaseController::writeNotice($pre_member->id,$title,$content);
                }
                if($model->links!=''){
                    return $this->redirect($model->links);
                }else {
                    $agent_msg = AdminAgentMessage::find()->where(['p_id'=>$pid,'user_id' => $uid])->one();
                    if($agent_msg) {
                        if($agent_msg->promo_code) {
                            return $this->redirect($agent_msg->promo_url);
                        }else{
                            Yii::$app->getSession()->setFlash('error', '系统出错！');
                            echo "<script>window.history.go(-1)</script>";return;
                        }
                    } else{
                        Yii::$app->getSession()->setFlash('error', '系统出错！');
                        echo "<script>window.history.go(-1)</script>";return;
                    }
                }
            }else{
                yii::$app->getSession()->setFlash('error', '提交失败，请重新提交！');
                echo "<script>window.history.go(-1)</script>";return;
            }
        }else{
            $userAgent = Yii::$app->request->userAgent;
            // QQ前面有个空格
            $res = strpos($userAgent, 'MicroMessenger') !== false ||
                (strpos($userAgent, 'MQQBrowser') !== false && strpos($userAgent, ' QQ') !== false);
            if ($res) {
                $this->layout = false;
                return $this->render('browser');
            }
            $sign = Yii::$app->request->get('sign');
            $uid = Yii::$app->request->get('uid');
            $pid = Yii::$app->request->get('pid');
            if(isset($sign)&&$sign==101){
                $model = AdminDaiProduct::findOne($pid);
                $apply_num = AdminDaiRecord::find()->where(['pid'=>$pid])->count();
                return $this->render('sub-product',compact('uid','model','apply_num','sign'));
            }
            $model = AdminDaiProduct::findOne($pid);
            $agent_msg = AdminAgentMessage::find()->where(['p_id'=>$pid,'user_id'=>$uid,'type'=>2])->one();
        }
        if($model){
            if($model->is_open==0){
                $url = Yii::$app->urlManager->createAbsoluteUrl(['share/loan-supermarket','uid'=>$uid]);
                return $this->redirect($url);
            }
            if($agent_msg){
                if($model->links==''&&$agent_msg->promo_url==''){
                    $url = Yii::$app->urlManager->createAbsoluteUrl(['share/loan-supermarket','uid'=>$uid]);
                    return $this->redirect($url);
                }else{
                    $apply_num = AdminDaiRecord::find()->where(['pid'=>$pid])->count();
                    return $this->render('sub-product',compact('uid','model','apply_num'));
                }
            }
            $apply_num = AdminDaiRecord::find()->where(['pid'=>$pid])->count();
            return $this->render('sub-product',compact('uid','model','apply_num'));
        }else{
            $url = Yii::$app->urlManager->createAbsoluteUrl(['share/loan-supermarket','uid'=>$uid]);
            return $this->redirect($url);
        }
    }

}
