<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/1/24
 * Time: 16:15
 */
namespace mobile\controllers;

use backend\models\AdminAgentMessage;
use backend\models\AdminArticle;
use backend\models\AdminBankCard;
use backend\models\AdminCommission;
use backend\models\AdminDaiRecord;
use backend\models\AdminDrawMoney;
use backend\models\AdminMember;
use backend\models\AdminWithdraw;
use common\controllers\PublicController;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\AdminRegions;
use backend\models\AdminDaiProduct;
use common\utils\CommonFun;
use common\models\WeChat;
use yii\helpers\Url;
class PageController extends Controller{
    public $request;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->request = Yii::$app->request;
        
    }
    public function actionSubProduct()
    {
        $this->getView()->title = '提交信息';
        $uid = $this->request->get('uid');
        $pid = $this->request->get('pid');
        $model = AdminDaiProduct::findOne($pid);
        $apply_num = AdminDaiRecord::find()->where(['pid'=>$pid])->count();
        $type = $this->request->get('type');
        $view = $type==1?'sub-product':'sub-product_bank';
        return $this->render($view,[
            'uid'=>$uid,
            'model'=>$model,
            'apply_num'=>$apply_num,
            //'dai_model'=>$dai_model,
        ]);
    }
}