<?php
namespace frontend\controllers;

use backend\models\AdminMember;
use common\controllers\PublicController;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\AdminRegions;
/**
 * Site controller
 */
class MemberController extends Controller
{
    /**
     * @inheritdoc
     */
    public $defaultAction='index';
    public $enableCsrfValidation = false ;
    public $user_id;
    public $user_info;
    public $AppID = 'wx54e7d01d4bdd34d9';
    public $AppSecret = 'ad0749e899c3178b1806518a0c99d708';
    public $request;
    public $session;
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * init
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->request = Yii::$app->request;
        $this->session = Yii::$app->session;
        if (strpos($_SERVER['HTTP_USER_AGENT'], 'MicroMessenger') !== false) {
            //微信登录
            if(!$this->session->get('user_id')) {
                $url = urlencode(Yii::$app->urlManager->createAbsoluteUrl(['member/we-chat-login']));
                $wx_url = "open.weixin.qq.com/connect/oauth2/authorize?appid=".$this->AppID."&redirect_uri=".$url."&response_type=code&scope=snsapi_userinfo&state=STATE#wechat_redirect";
                $this->redirect($wx_url);
                Yii::$app->end();
            }else{
                $this->user_id = $this->session->get('user_id');
                $this->user_info = AdminMember::findOne($this->user_id);
            }
        }
    }

    /**
     * 微信login
     */
    protected function weChatLogin()
    {
        $code = $this->request->get('code');
        $url_1 = "https://api.weixin.qq.com/sns/oauth2/access_token?appid=".$this->AppID."&secret=".$this->AppSecret."&code=".$code."&grant_type=authorization_code";
        $refresh_token = $this->getData($url_1)->refresh_token;
        $url_2 = "https://api.weixin.qq.com/sns/oauth2/refresh_token?appid=".$this->AppID."&grant_type=refresh_token&refresh_token=".$refresh_token;
        $openid = $this->getData($url_2)->openid;
        $access_token = $this->getData($url_2)->access_token;
        $url_3 = "https://api.weixin.qq.com/sns/userinfo?access_token=".$access_token."&openid=".$openid."&lang=zh_CN";
        $openid = $this->getData($url_3)->openid;
        $nickname = $this->getData($url_3)->nickname;
        $head_img  = $this->getData($url_3)->headimgurl ;
        $model = AdminMember::find()->where(['openid'=>$openid]);
        //如果存在这条数据
        if($model) {
            $model->nickname = $nickname;
            $model->pic = $head_img;
            $model->login_time = time();
            if($model->save()) {
                $this->session->set('user_id',$model->id);
            }
        }else {
            $model->nickname = $nickname;
            $model->pic = $head_img;
            $model->openid = $openid;
            $model->invitation = PublicController::getInvitation();
            $model->created_time = time();
            if($model->save()) {
                $this->session->set('user_id',$model->id);
            }else{
                $this->weChatLogin();
            }
        }
    }

    /**
     * 返回接口数据
     * @return json
     */
    protected function getData($url)
    {
        return json_encode(file_get_contents($url));
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

}
