<?php
namespace console\common\controllers;
use backend\models\AdminMember;
use backend\models\AdminSetting;
use common\models\WeChat;
use Yii;
use yii\web\Controller;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
class PublicController extends Controller
{

    public static $user_id;
    public static $user_info;
    /**
     * init
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        self::$user_id = Yii::$app->session->get('user_id');
        self::$user_info = AdminMember::findOne($this->user_id);
    }

    /**
     *过滤公共方法
     * $type  1是纯文本过滤，2是HTML过滤
     */
    public static function filter($text, $type=1)
    {
        if($type ==1 ) {
            return Html::encode($text);
        }else if($type == 2) {
            return HtmlPurifier::process($text);
        }
    }

    public static function filter_decode($text,$type=1){
        if($type==1){
            return htmlspecialchars_decode($text);
        }else{
             return HtmlPurifier::process($text);
        }
    }
    /**
     *生成邀请码
     */
    public static function getInvitation()
    {
        $code = substr(md5(uniqid(rand(),1)),0,16);
        if(AdminMember::find()->where(['invitation'=>$code])->one()) {
            self::getInvitation();
        }
        return $code;
    }

    public static function file($file,$name='pic')
    {
        $uploaddir = 'uploads/img/';
        $info=pathinfo($file['name'][$name],PATHINFO_EXTENSION);
        $dir=$uploaddir .date('Ymd').rand(10000,99999).'.'.$info;
        if (move_uploaded_file($file['tmp_name'][$name],$dir)) {
            $re['dir']='/'.$dir;
            $re['msg']="上传成功";
            $re['status']=200;
            return $re['dir'];
        } else {
            $re['msg']="上传失败";
            return false;
        }
    }

    /**
     * 截取并处理字符串
     * $str 处理的字符串
     * $len 截取的长度
     * $add 后面是否加...
     */
    public static function subStr($str,$len=0,$add=true){
        if( $len < mb_strlen($str,'utf8') && $len && $add) {
            $str = mb_substr($str,0,$len,'utf-8').'...';
        } else {
            $str = mb_substr($str,0,$len,'utf-8');
        }
        return $str;
    }

    /**
     * 获取设备信息
     * @return integer
     * 1,安卓，2,ios,3,其他
     */
    public static function getSystem()
    {
        $agent = strtolower($_SERVER['HTTP_USER_AGENT']);
        $is_pc = (strpos($agent, 'windows nt')) ? true : false;
        $is_mac = (strpos($agent, 'mac os')) ? true : false;
        $is_iphone = (strpos($agent, 'iphone')) ? true : false;
        $is_android = (strpos($agent, 'android')) ? true : false;
        $is_ipad = (strpos($agent, 'ipad')) ? true : false;
        if($is_android) {
            return 1;
        }else if($is_iphone) {
            return 2;
        }else {
            return 3;
        }
    }
    
    public static function build_form($url, $data){
        $sHtml = "<!DOCTYPE html><html><head><title>Waiting...</title>";
        $sHtml.= "<meta http-equiv='content-type' content='text/html;charset=utf-8'></head>
      <body><form id='lakalasubmit' name='lakalasubmit' action='".$url."' method='POST'>";
        foreach($data as $key => $value){
            $sHtml.= "<input type='hidden' name='".$key."' value='".$value."' style='width:90%;'/>";
        }
        $sHtml .= "</form>";
        $sHtml .= "<script>document.forms['lakalasubmit'].submit();</script></body></html>";
        exit($sHtml);
    }

    /**
     * 发送短信
     */
    public static function sendSms($tel,$param,$temp,$sign='卡农社区')
    {
        require_once ROOT.'/sms/TopSdk.php';
        //$code=rand(100000,999999);
        $appkey = self::getSysInfo(5);
        $secret = self::getSysInfo(6);
        $c = new \TopClient;
        $c->appkey = $appkey;
        $c->secretKey = $secret;
        $c->format = 'json';
        $req = new \AlibabaAliqinFcSmsNumSendRequest;
        //$req->setExtend($code);
        $req->setSmsType('normal');
        $req->setSmsFreeSignName($sign); //发送的签名
        $req->setSmsParam($param);//根据模板进行填写
        $req->setRecNum($tel);//接收着的手机号码
        $req->setSmsTemplateCode($temp);//短信模板
        $resp = $c->execute($req);
        return $resp->result->err_code;
    }

    // 鑫e贷发送短信接口
    public static function setCodes($tel,$random)
    {
        $statusStr = array(
            "0" => "短信发送成功",
            "-1" => "参数不全",
            "-2" => "服务器空间不支持,请确认支持curl或者fsocket，联系您的空间商解决或者更换空间！",
            "30" => "密码错误",
            "40" => "账号不存在",
            "41" => "余额不足",
            "42" => "帐户已过期",
            "43" => "IP地址限制",
            "50" => "内容含有敏感词"
        );
        $smsapi = "http://api.smsbao.com/";
        $user = "XSJT666"; //短信平台帐号
        $pass = md5("Xs20180308"); //短信平台密码
        $content="【鑫e贷】".$random."为您的验证码，请于3分钟内填写。如非本人操作，请忽略本短信。";//要发送的短信内容
        $phone = $tel;//要发送短信的手机号码
        $sendurl = $smsapi."sms?u=".$user."&p=".$pass."&m=".$phone."&c=".urlencode($content);
        $result =file_get_contents($sendurl) ;
        if($result=='0'){
            return true;
        } else {
            return false;
        }
    }
    // 腾讯云发送短信接口
     public static function setCodes2($phone, $tpl_id, $random)
        {
            $sj = 3;
            $curTime = time();
            $wholeUrl = "https://yun.tim.qq.com/v5/tlssmssvr/sendsms?sdkappid=1400114866&random=" . $random;
            // 按照协议组织 post 包体
            $data = new \stdClass();
            $tel = new \stdClass();
            $tel->nationcode = "" . "86";
            $tel->mobile = "" . $phone;
            $data->tel = $tel;
            $data->sig = hash("sha256",
                "appkey=ec0585ca2365ad0b137ef9368d9ffea6&random=" . $random . "&time="
                . $curTime . "&mobile=" . $phone, FALSE);
            $data->tpl_id = $tpl_id;
            $data->params = array($random, $sj);
            $data->time = $curTime;
            //$data->sign = '云肆网络';//如果只有一个则不需要签名
            $data->extend = '';
            $data->ext = '';
            $curl = curl_init();
            curl_setopt($curl, CURLOPT_URL, $wholeUrl);
            curl_setopt($curl, CURLOPT_HEADER, 0);
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($curl, CURLOPT_POST, 1);
            curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($data));
            curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0);
            curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);
            $ret = curl_exec($curl);
            $res = json_decode($ret, true);
            if ($res['errmsg'] == 'OK') {//发送成功
                return true;
            } else {
                return false;
            }
        }



     public static function setCodesBak($tel,$param,$temp)
     {
            //发送链接（用户名，密码，手机号，内容）
        // echo  $tel;exit;
            $url = "https://sms.qianhaishuliang.com/sms_platform/receiveController?";
            $mobilePhone =$tel;
            $serviceType=$temp;
            $params=$param;
            $sys ='33';
            $sigkey ='7f79150aa903418f989e18a5cc71a4ee';
            $sige =$sys.$serviceType.$mobilePhone.$sigkey;
            $siges =strtoupper(MD5($sige)); //将字符串小写转换成大写
            $data=array
            (
                'mobilePhone'=>$mobilePhone,//手机号码
                'serviceType'=>$serviceType,//模板编号
                'asyn'=>false,//是否异步(一版传false)
                'sys' =>$sys,//调用系统编号
                'data'=>$params,
                'sige'=>$siges,//签名信息md5(sys+serviceType+mobilePhone+sigkey)
            );
            $datas =json_encode($data);
            $curl = curl_init();
            curl_setopt($curl, CURLOPT_URL, $url);
            curl_setopt($curl, CURLOPT_HEADER, 0);
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($curl, CURLOPT_POST, 1);
            curl_setopt($curl, CURLOPT_POSTFIELDS,json_encode($data));
            // curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0);
            // curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);
            $ret = curl_exec($curl);
            $res = json_decode($ret, true);
            if($res['result']==0000){
                 return true;
            }else{
                 return false;
            }
    }

    /**
     * 获取配置信息
     */
    public static function getSysInfo($id)
    {
        return AdminSetting::findOne($id)->val;
    }

    /**
     * 生成菜单
     */
    public static function setMenu()
    {
        /*$menu = '{
            "button":[
                {
                    "name":"加入会员",
                    "sub_button":[
                        {
                            "name": "购买会员",
                            "type": "view",
                            "url": "'.Yii::$app->urlManager->createAbsoluteUrl(['list/buy-agent']).'"
                        },
                        {
                            "name": "我要办卡",
                            "type": "view",
                            "url": "'.Yii::$app->urlManager->createAbsoluteUrl(['list/card']).'"
                        },
                        {
                            "name": "提额技巧",
                            "type": "view",
                            "url": "'.Yii::$app->urlManager->createAbsoluteUrl(['list/news','cat_id'=>5]).'"
                        },
                        {
                            "name": "银行快贷",
                            "type": "view",
                            "url": "'.Yii::$app->urlManager->createAbsoluteUrl(['list/bank-loan','type'=>1]).'"
                        },
                    ]

                },
                {
                    "name":"个人中心",
                    "sub_button":[
                        {
                            "name": "我的后台",
                            "type": "view",
                            "url": "'.Yii::$app->urlManager->createAbsoluteUrl(['member/index']).'"
                        },
                        {
                            "name": "最新口子",
                            "type": "view",
                            "url": "'.Yii::$app->urlManager->createAbsoluteUrl(['list/news','cat_id'=>4]).'"
                        },
                        {
                            "name": "二次贷",
                            "type": "view",
                            "url": "'.Yii::$app->urlManager->createAbsoluteUrl(['list/product','type'=>1]).'"
                        },
                    ]
                },
                {
                     "name": "我的代言码",
                     "type": "view",
                     "url": "'.Yii::$app->urlManager->createAbsoluteUrl(['list/buy-agent']).'"
                }
            ]
        }';*/

        $menu = '{
            "button":[
                {
                    "name":"加入会员",
                    "sub_button":[
                    {	
                        "type":"view",
                        "name":"购买会员",
                        "url":"'.Yii::$app->urlManager->createAbsoluteUrl(['list/buy-agent']).'"
                    },
                    {	
                        "type":"view",
                        "name":"我要办卡",
                        "url":"'.Yii::$app->urlManager->createAbsoluteUrl(['list/card']).'"
                    },
                    {	
                        "type":"view",
                        "name":"提额技巧",
                        "url":"'.Yii::$app->urlManager->createAbsoluteUrl(['list/news','cat_id'=>5]).'"
                    },
                    {	
                        "type":"view",
                        "name":"我要贷款",
                        "url":"http://fenxiao.qianhaishuliang.com/index.php?r=index%2Fwantloan"
                    }]
                },
                {	
                    "type":"click",
                    "name":"我的代言码",
                    "key":"QRCODE"
                },
                {
                    "name":"个人中心",
                    "sub_button":[
                    {	
                        "type":"view",
                        "name":"我的后台",
                        "url":"'.Yii::$app->urlManager->createAbsoluteUrl(['member/index']).'"
                    },
                    {
                        "type":"view",
                        "name":"最新口子",
                        "url":"'.Yii::$app->urlManager->createAbsoluteUrl(['list/news','cat_id'=>4]).'"
                    },
                    {
                        "type":"view",
                        "name":"二级贷",
                        "url":"'.Yii::$app->urlManager->createAbsoluteUrl(['index/index','type'=>1]).'"
                    }]
                }
            ]
        }';
        $weChat = new WeChat();
        return $weChat->menuSet($menu);
    }

    /**
     * @param $temp
     * @param $openid
     * @param $url
     * @param $data
     * @return bool
     */
    public static function sendTempMsg($temp,$openid,$data,$url='')
    {
        $post_data = [
            "touser"=>$openid,
            "template_id"=>$temp,
            "url"=>$url,
            "data"=> $data
        ];
        $weChat = new WeChat();
        $post_data = json_encode($post_data);
        return $weChat->sendTempInfo($post_data);
    }

    /**
     * 读取网络上面图片，保存到本地
     * @param $url
     * @param string $filename
     * @return bool|string
     */
    public static function createImage($url, $filename = "")
    {
        $head_url = substr($url,0,strripos($url, "/"))."/46";
        $img = file_get_contents($head_url);
        file_put_contents($filename,$img);
        return $filename;//返回新的文件名

        /*if ($url == ""):return false;
        endif;
        //如果$url地址为空，直接退出
        if ($filename == "") {
            //如果没有指定新的文件名
            $ext = strrchr($url, ".");
            //得到$url的图片格式
            if ($ext != ".gif" && $ext != ".jpg"):return false;
            endif;
            //如果图片格式不为.gif或者.jpg，直接退出
            $filename = date("dMYHis") . $ext;
            //用天月面时分秒来命名新的文件名
        }
        ob_start();//打开输出
        readfile($url);//输出图片文件
        $img = ob_get_contents();//得到浏览器输出
        ob_end_clean();//清除输出并关闭
        //$size = strlen($img);//得到图片大小
        $fp2 = @fopen($filename, "a");
        fwrite($fp2, $img);//向当前目录写入图片文件，并重新命名
        fclose($fp2);
        return $filename;//返回新的文件名*/
    }

    /**
     * 生成二维码，保存到本地
     * @param string $url
     * @param bool $file_name
     */
    public static function qrCode($url='',$file_name=false,$size=11)
    {
        require ROOT.'/phpqrcode/qrlib.php';
        //设置 header 头,直接输出图片
        Yii::$app->response->headers->set('Content-Type', 'image/png');
        //根据参数生成二维码 , 将其第二个参数值设为 false ,也就是不输出图片文件
        \QRcode::png($url, $file_name, "L", $size, 1);
        //die();
    }

    public static function qrCode2($url='',$file_name=false,$size=11)
    {
        require ROOT.'/phpqrcode/qrlib.php';
        //设置 header 头,直接输出图片
        Yii::$app->response->headers->set('Content-Type', 'image/png');
        //根据参数生成二维码 , 将其第二个参数值设为 false ,也就是不输出图片文件
        \QRcode::png($url, $file_name, "L", $size, 1);
        //die();
    }

    /**
     * 判断用户是否关注公众号
     * @param $openid
     * @return int
     */
    public static function isSubscribe($openid)
    {
        $weChat = new WeChat();
        $access_token = $weChat->getAccessToken();
        $url = 'https://api.weixin.qq.com/cgi-bin/user/info?access_token='.$access_token.'&openid='.$openid.'&lang=zh_CN';
        $data = json_decode(file_get_contents($url));
        $subscribe = 0;
        if(isset($data->subscribe)) {
            $subscribe = $data->subscribe;
        }
        return $subscribe;
    }
    /*  $grade 等级
        $money 佣金
    */
    public static function commission($money, $grade, $num)
    {
        $rate = explode(',', PublicController::getSysInfo(7));    //1级 金牌
        $rate2 = explode(',', PublicController::getSysInfo(12));  //2级 银牌
        $rate3 = explode(',', PublicController::getSysInfo(13)); //3级  铜牌 0 1
        if ($grade != 0) {
            if ($grade == 3) { //  金牌 一 二 三 级
                foreach ($rate as $key => $value) {
                    if ($key == ($num - 1)) {
                        $commisssion = number_format($money * $value / 100, 2, '.', '');
                    }
                }
            }
            if ($grade == 2) { //  银牌 一 二 三 级
                foreach ($rate2 as $key => $value) {
                    if ($key == ($num - 1)) {
                        $commisssion = number_format($money * $value / 100, 2, '.', '');
                    }
                }
            }
            if ($grade == 1) { //  铜牌 一 二 三 级
                foreach ($rate3 as $key => $value) {
                    if ($key == ($num - 1)) {
                        $commisssion = number_format($money * $value / 100, 2, '.', '');
                    }
                }
            }
        } else {
            $commisssion = 0;
        }
        return $commisssion;
    }

}

?>